---
- hosts: webservers
  remote_user: runblueprint
  tasks:
  - name: Create checkout directory
    file:
        path: '~/checkout/{{ folder }}'
        state: 'directory'
  - name: Pull new code from Git repo
    git:
      repo: 'https://github.com/supermitch/runblueprint.com.git'
      dest: 'checkout/{{ folder }}'
  - name: Copy files to public folder
    command: 'git --work-tree=/home/runblueprint/{{ folder }}/public --git-dir=/home/runblueprint/checkout/{{ folder }}/.git checkout -f'
