# Check python version
# cd /test.runblueprint.com/public/runblueprint
# Create venv
# Pip install -r requirements

# Collect Static:
# [server]$ cd /home/runblueprint/test.runblueprint.com/public
# [server]$ mkdir static
# [server]$ cd /home/runblueprint/test.runblueprint.com/runblueprint/
# [server]$ python manage.py collectstatic
#
# Set ENV vars:
# DJANGO_DB_NAME
# DJANGO_DB_USERNAME
# DJANGO_DB_PASSWORD
# DJANGO_DB_HOSTNAME
# DJANGO_DB_PORT
# DJANGO_SECRET_KEY
#
# touch tmp/restart.txt
# touch passenger.w
