#!/usr/bin/env ansible-playbook
---
- name: Deploy Django App
  hosts: all
  remote_user: runblueprint
  vars_prompt:
    - name: proceed
      prompt: "Are you sure you want to deploy to Prod? (y|n)"
      default: n
      private: no
  roles:
    - django_app
