- name: Create logging directory
  file:
    path: "/home/runblueprint/{{ domain }}/runblueprint/log"
    state: directory

- name: Create repository checkout directory
  file:
    path: "/home/runblueprint/checkout/{{ domain }}"
    state: directory

- name: Git pull fresh code
  git:
    repo: https://github.com/supermitch/runblueprint.com.git
    dest: "/home/runblueprint/checkout/{{ domain }}"

- name: Git checkout files to work tree
  command: >
    git
    "--git-dir=/home/runblueprint/checkout/{{ domain }}/.git"
    "--work-tree=/home/runblueprint/{{ domain }}"
    checkout -f

- name: Touch Restart
  file:
    path: "/home/runblueprint/{{ domain }}/tmp/restart.txt"
    state: touch
